[package]
name            =  "rsdk"
version         =  "0.0.1"
description     =  "Rust/DPDK"
authors         = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license         =  "MIT"
repository      =  "github: https://github.com/ponyatov/rsdk"
edition         =  "2024"

[build-dependencies]
cmake           = "0.1"
bindgen         = "0.72"

[dependencies]
const_format    = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc            = "0.2"
memmap2         = "0.9"
